---
###############################################################################
# This playbook utilizes the Ansible network engine role and a number of other
# modules.
#
# This playbook
#   - executes a "show arp" command on the designated group
#   - formats and saves the output to a text file
#   - loads the properly formatted show command output
#   - uses the network engine textfsm_parser to parse the output
#   - and defines a list of vrf names for the device and outputs that list to
#     stdout
#
# Ultimately that list will be used to get the ARP table from each VRf
#
#
# EXECUTION:
# ansible-playbook -i hosts ansible_get.yml --ask-vault-pass
#
# To display the output variable run the playbook with a single v
# ansible-playbook -i hosts ansible_get.yml --ask-vault-pass -v
#
# Vault Password: Cisco123
###############################################################################

- hosts: cisco_xe
  gather_facts: False
  connection: network_cli

  # Creating the vrf_list variable and seeding it with default
  vars:
    vrf_list: ['default']

  roles:
    - ansible-network.network-engine

  tasks:

    - name: Exceute show vrf command
      ios_command:
        commands: "{{ item }} "
      with_items:
          - "show vrf"
      register: output
      ignore_errors: yes

    - name: Debug with -v to show output contents only when debugging
      debug:
        var: output
        verbosity: 1

    - name: Show the vrf command output with stdout_lines
      debug:
        msg: "{{ output.results.0.stdout_lines.0 }}"

    - name: Extract the formatted show vrf output from file for correct parsing via TextFSM
      set_fact:
        vrf_content: "{{ output.results.0.stdout_lines.0 }}"


    - name: Use Network Engine Role textfsm_parser to Parse VRF Output and store in variable vrf_facts
      textfsm_parser:
        file: './ntc-templates/templates/cisco_ios_show_vrf.textfsm'
        content: "{{ vrf_content }}"
        name: vrf_facts

    - name: Show contents of variable vrf_facts
      debug:
        var: vrf_facts

    - name: Show VRF names only
      debug:
        msg: "{{ item['NAME'] }}"
      with_items:
        - "{{ vrf_facts }}"

    - name: Append new VRFS to list of VRF names
      set_fact:
        vrf_list: "{{ vrf_list }} + ['{{ item['NAME'] }}' ]"
      with_items:
        - "{{ vrf_facts }}"

    - name: Show Complete List of VRF Names
      debug: var=vrf_list