---
###############################################################################
# This playbook utilizes the Ansible network engine role and a number of other
# modules.
#
# This playbook
#   - executes a "show arp" command on the designated group
#   - formats and saves the output to a text file
#   - loads the properly formatted show command output
#   - uses the network engine textfsm_parser to parse the output
#   - and defines a list of vrf names for the device and outputs that list to
#     stdout
#
# Ultimately that list will be used to get the ARP table from each VRf
#
#
# EXECUTION:
# ansible-playbook -i hosts ansible_get.yml --ask-vault-pass
#
# To display the output variable run the playbook with a single v
# ansible-playbook -i hosts ansible_get.yml --ask-vault-pass -v
#
# Vault Password: Cisco123
###############################################################################

- hosts: sbx_nxos
  gather_facts: False
  connection: network_cli

  vars:
    find_network: '10.99.99.1'
    find_mask:  '32'
    found_prefix: 'No'
    found_default: 'No'


  roles:
    - ansible-network.network-engine

  tasks:
    - name: Exceute show ip route command
      ios_command:
        commands: "{{ item }} "
      with_items:
          - "show ip route"
      register: output
      ignore_errors: yes

    - name: Debug with -v to show output contents only when debugging
      debug:
        var: output
        verbosity: 1

    - name: Show the command output with stdout_lines
      debug:
        var: "{{ output.results.0.stdout }}"

    - name: Extract the SEMI FORMATTED show command TEXT output
      set_fact:
        showcmd_content: "{{ output.results.0.stdout[0] }}"

    - name: Show the SEMI FORMATTED show command TEXT to be sent to the textfsm_parser module
      debug:
        var: showcmd_content

    - name: Use Network Engine Role textfsm_parser to Parse Output and store in variable cmd_facts
      textfsm_parser:
        file: './ntc-templates/templates/cisco_nxos_show_ip_route.textfsm'
        content: "{{ showcmd_content }}"
        name: cmd_facts

    - name: Show contents of PARSED CONTENTS in variable cmd_facts
      debug:
        var: cmd_facts

    - name: Set to True if Default Route found
      set_fact:
        found_default: 'Yes'
      when: "({{ item['NETWORK'] }} == '0.0.0.0')"
      with_items: "{{ cmd_facts }}"

    - name: "Set to True if {{ find_network }}/{{ find_mask }} "
      set_fact:
        found_default: 'Yes'
        when: "({{ item['NETWORK'] }} == find_network and {{ item['MASK'] }} == find_mask)"
        with_items: "{{ cmd_facts }}"

    - name: 1 - Show Total Number of Routes
      debug:
        msg: "1. Total Number of Routes: {{ cmd_facts|length }}"

    - name: 2 - Determine if there is a Default Route
      debug:
        msg: "2. Is there a default route?: {{ found_default }}"

    - name: "3 - Determine if {{ find_network }}/{{ find_mask }} is in the routing table"
      debug:
        msg: "3. Is {{arguments.prefix}} in the routing table:: {{ found_prefix }}"


#    - name: Append new VRFS to list of VRF names
#      set_fact:
#        vrf_list: "{{ vrf_list }} + ['{{ item['NAME'] }}' ]"
#      with_items:
#        - "{{ vrf_facts }}"
#
#    - name: Show Complete List of VRF Names
#      debug: var=vrf_list